development:
  MYSQL_DATABASE: 'Web_tmi_develop'
  MYSQL_USERNAME: 'root'
  MYSQL_PASSWORD: '1234567890'
test:
  MYSQL_DATABASE: 'Web_tmi_test'
  MYSQL_USERNAME: 'root'
  MYSQL_PASSWORD: '1234567890'
production:
  MYSQL_DATABASE: 'Web_tmi'
  MYSQL_USERNAME: 'root'
  MYSQL_PASSWORD: '1234567890'

